Car 52 sign up page
atom-squad/actnow-app pull request #6
Opened 2023-03-01 01:17 UTC by tanyag183

<img width="356" alt="Screen Shot 2023-02-28 at 5 13 38 PM" src="https://user-images.githubusercontent.com/99174929/222019913-faba1655-89ec-4838-9ad8-e05b0c6784ba.png">
<img width="361" alt="Screen Shot 2023-02-28 at 5 14 28 PM" src="https://user-images.githubusercontent.com/99174929/222019917-d47cf0b0-c035-4cd9-8674-c5970287457e.png">
<img width="364" alt="Screen Shot 2023-02-28 at 5 14 47 PM" src="https://user-images.githubusercontent.com/99174929/222019918-506225a8-c144-40b8-9471-813381f05c4e.png">

2023-03-01 19:06 UTC, luferupa reviewed
The screenshots looks so nice. I propose some changes on comments

2023-03-01 19:06 UTC, luferupa commented on components/SelectOrganization.tsx
> +const SelectOrganization = () => {
@tanyag183 it looks nice. But if you see, the component has exactly the same structure as the SelectDepartment component. So, you can leave just 1 Component and reuse it for department and organization, passing as params the label/placeholder message, the value (department or organization), and the set method.
This way, the states should be defined in the SignUp screen.

2023-03-01 19:06 UTC, luferupa commented on components/SignUpOneScreen.tsx
> +  const styles = {
We should move the styles to separate scss files for each screen and import it here. It's also a good practice to give classNames to the elements so that you can add the styles in the css specifically for the corresponding class.

2023-03-01 19:06 UTC, luferupa commented on components/SignUpTwoScreen.tsx
> +  const styles = {
Same comment that the one in the 1st screen for signup

2023-03-01 19:06 UTC, luferupa commented on screens/LogIn.tsx
>  const styles = StyleSheet.create({
Same thing about the external scss and the classNames

2023-03-02 18:53 UTC, luferupa commented on scss/LogInStyles.tsx
> +export default StyleSheet.create ({
Tanya, what if you just create these files as .scss and remove the import and export lines, just leaving the styles? It should work.
Because as it is right now, I think we are not really implementing sass.

2023-03-02 18:54 UTC, luferupa requested changes
Tanya, what if you just rename the style files as .scss and remove the import and export lines, just leaving the styles? It should work.
Because as it is right now, I think we are not really implementing sass.

2023-03-03 00:22 UTC, KariGarcia commented on components/SignUpOneScreen.tsx
> +  const styles = {
Thats a great sugestion! only thing is that in this case, we are not using sass yet, we use the default syle objects from react native

2023-03-03 00:22 UTC, KariGarcia commented on scss/LogInStyles.tsx
> +export default StyleSheet.create ({
Can you be more specific? I dont think its gonna work, yeah we are not using sass so the way we can have the styles object is by importing/exporting if its in a different file

2023-03-03 02:12 UTC, luferupa commented on scss/LogInStyles.tsx
> +export default StyleSheet.create ({
got it. So keep it as it is, @tanyag183

2023-03-03 02:13 UTC, tanyag183 commented on scss/LogInStyles.tsx
> +export default StyleSheet.create ({
Sorry, I think I misnamed the folder. It should be css instead of scss.

2023-03-03 02:16 UTC, luferupa approved these changes

2023-03-03 09:40 UTC, merged